// app/layout.js
import { Poppins } from "next/font/google";
import NavBar from "./components/NavBar/NavBar";
import Galaxy from "./components/Galaxy/Galaxy";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body
        className={`${poppins.className} relative min-h-[100svh] bg-black text-white`}>

        {/* NAVBAR: tetap di atas saat scroll */}
        <NavBar className="fixed top-0 left-0 w-full z-[9999]" />

        {/* KONTEN: beri jarak setinggi navbar (h-16 = 64px → pt-16) */}
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
